### ISSUE TITLE
New Command Idea.

### ISSUE THREAD

**Issue by greymesa** [Shadowevil015/keith#1]
Hey, I was wondering if a command like <a href="#code">this</a> could be implemented. I would add it myself and make a PR but I still don't understand these new slash commands and the Discord.js handler associated with it.
<br>
<a id="code"></a>
```javascript
  const puppeteer = require("puppeteer");
    puppeteer
      .launch({ 
        defaultViewport: {    // Define the size of the screenshot/headless browser
        width: 1920,
        height: 1080,
      },
  })
  .then(async (browser) => {
    const page = await browser.newPage();
    await page.goto("map.ccnetmc.com"); // Define the url
    await page.click (nations-map)  // Click on the nations button to open the nations map (found by element id)
    await setTimeout(func, 3000) // Delay in order for the page to load
    await page.screenshot({ path: "map.png" }); // Screenshot and save the file as map.png. The path can be configured
    await browser.close(); // Close the headless browser
  });
```
<br>
Thanks in advance!

-greymesa
(grey#3562 on discord)

**Comment by greymesa** [comment]
Ah I see.

No worries I can explain.

My suggestion uses a library called Puppeteer which is a headless browser with connectivity to node.js.
The code I sent above loads the dynamap website, finds and clicks on the nations button, waits 3 seconds for the site to load, then screenshot it and save it as map.png.

I've added comments to the code so you can edit it to your liking.

Hope this helps you out!

**Comment by greymesa** [comment]
Glad to help!

**Comment by Shadowevil015** [comment]
I've added this command! You can now get a "full" picture of the map when you use the command `/fullmap` !

I'll mark this as closed, but I'm also going to look into the viability of adding this to the town search command also. :)

**Comment by greymesa** [comment]
Niceee!

Yet again, glad to help!
